version: "3.7"

services:
  app:
    build:
      args:
        user: fuad
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ereport
    container_name: ereport-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ereport

  db:
    image: mysql:5.7
    container_name: ereport-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ereport

  nginx:
    image: nginx:alpine
    container_name: ereport-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ereport

networks:
  ereport:
    driver: bridge